### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by StephanGR**
I've added : 

- contributors and downloads counters
- Summary
- Debugging section if people wants to see logs

### CODE REVIEW

**Comment by mvdwetering** [comment]
How does the download counter work?
It shows 136 downloads for me, but Home Assistant analytics shows already 366 installations (and lots of people don't have analytics enabled). 

So the number seems kind of random, I would like to understand what it is showing. Is it "forever" downloads? Or like last month? Or per version? If the number does not make sense I would prefer not to include it.

The other changes are fine 👍

**Comment by StephanGR** [comment]
`/total.svg` represent the total of all downloads
If you want specific version, you can edit the link and add `v1.21.1` just before `/total.svg`
it will be something like that : `https://img.shields.io/github/downloads/mvdwetering/huesyncbox/v1.21.1/total.svg`

Or if you want always the latest version : `https://img.shields.io/github/downloads/mvdwetering/huesyncbox/latest/total.svg`

But I can remove it if you want :)

**Comment by mvdwetering** [comment]
Lets leave the downloads out as it does not seem to represent the usage and not really sure why it would be useful otherwise.

**Comment by StephanGR** [comment]
All checks are ok, and I've removed the downloads line !

**Pull request merged**
